engines: 
  eslint:
    enabled: true
    checks:
      fatal:
        enabled: false  
ratings:
   paths:
   - "**.js"
exclude_paths:
  - "jasmine/"
  - "spec/"
  - "gulpfile.js"
  - "lib/"
  - "*.js"
  - "coverage/"
  - "src/app.js"